include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    await_only_futures: true
    public_member_api_docs: false
    prefer_void_to_null: false
    avoid_print: false
    unawaited_futures: true
