name: kiri_check
description: Property-based testing for Dart.
version: 0.9.0
repository: https://github.com/szktty/kiri-check

environment:
  sdk: ^3.2.6

dependencies:
  collection: ^1.18.0
  date_kit: ^1.0.2
  meta: ^1.14.0
  mt19937: ^0.1.0
  test: ^1.25.4
  timezone: ^0.9.3

dev_dependencies:
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
