name: kiri_check
description: A testing library for property-based testing, enabling custom test data generation, testing stateful systems, and integrating seamlessly with package:test.
version: 1.1.0
repository: https://github.com/szktty/kiri-check

environment:
  sdk: ^3.4.0

dependencies:
  collection: ^1.19.0
  date_kit: ^1.0.2
  meta: ^1.15.0
  test: ^1.25.7
  timezone: ^0.9.3
  universal_platform: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  very_good_analysis: ^5.1.0
