name: Build

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - release/*
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test